[tool.black]
line-length = 100
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
line_length = 100
multi_line_output = 11

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py38

[testenv]
deps = -rrequirements-dev.txt
commands =
    coverage run -m pytest
    coverage report
    covergae erase
"""
